spring.application.name=energiai-api

# URL del servicio de Machine Learning (FastAPI)
ml.service.url=http://127.0.0.1:8000

# Tarifa base utilizada para el calculo financiero (USD por kWh)
energia.tarifa-usd=0.75